# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.12 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================

WX_CONFIG   = /usr/$(ARCH)-w64-mingw32/lib/wx/config/$(ARCH)-w64-mingw32-msw-ansi-static-$(V)
V           = 3.2
ARCH        = x86_64
CXX         = $(ARCH)-w64-mingw32-g++
CC          = $(ARCH)-w64-mingw32-gcc
WINDRES     = $(ARCH)-w64-mingw32-windres
STRIP       = $(ARCH)-w64-mingw32-strip
WXDEBUGFLAG :=-3.2-x86_64-w64-mingw32

# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# C++ compiler
CXX = `$(WX_CONFIG) --cxx`
#CXX = g++

# Standard flags for C++
CXXFLAGS ?= -O3 -s
#CXXFLAGS ?=

# Standard preprocessor flags (common for CC and CXX)
CPPFLAGS ?= `$(WX_CONFIG) --cppflags`
#CPPFLAGS ?=

# Standard linker flags
LDFLAGS ?= -static `$(WX_CONFIG) --libs`
#LDFLAGS ?=

# What type of library to build? [0,1]
SHARED ?= 0

# Used toolkit [MSW,GTK]
TOOLKIT ?= MSW

# GTK+ toolkit version [,2]
TOOLKIT_VERSION ?=

# Build wxUniversal instead of native port? [0,1]
WXUNIV ?= 0

# Compile Unicode build of wxWidgets? [0,1]
UNICODE ?= 0
#UNICODE ?= 1

# Type of compiled binaries [debug,release]
BUILD ?= release
#BUILD ?= debug

# Should debugging info be included in the executables? The default value
# "default" means that debug info will be included if BUILD=debug
# and not included if BUILD=release. [0,1,default]
DEBUG_INFO ?= default

# Value of wxDEBUG_LEVEL. The default value is the same as 1 and means that all
# but expensive assert checks are enabled, use 0 to completely remove debugging
# code. [0,1,default]
DEBUG_FLAG ?= 1

# Multiple libraries or single huge monolithic one? [0,1]
MONOLITHIC ?= 0

# Build GUI libraries? [0,1]
USE_GUI ?= 1

# Build wxWebView library (USE_GUI must be 1)? [0,1]
USE_WEBVIEW ?= 1

# Build multimedia library (USE_GUI must be 1)? [0,1]
USE_MEDIA ?= 1

# Build wxStyledTextCtrl library (USE_GUI must be 1)? [0,1]
USE_STC ?= 1

# Enable exceptions in compiled code. [0,1]
USE_EXCEPTIONS ?= 1

# Enable run-time type information (RTTI) in compiled code. [0,1]
USE_RTTI ?= 1

# Enable threading in compiled code. [0,1]
USE_THREADS ?= 1

# Enable wxCairoContext for platforms other than Linux/GTK. [0,1]
USE_CAIRO ?= 0

#
WX_LIB_FLAVOUR ?=

# Name of your custom configuration. This affects directory
# where object files are stored as well as the location of
# compiled .lib files and setup.h under the lib/ toplevel directory.
CFG ?=

